AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.7
      CodeUri: src
      Timeout: 600

  # ImageFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     PackageType: Image
  #     ImageConfig:
  #       Command:
  #         - main.handler
  #   Metadata:
  #     DockerTag: function
  #     DockerContext: ./PythonImage
  #     Dockerfile: Dockerfile
  #     DockerBuildArgs:
  #       BASE_RUNTIME: '3.8'