name: Pipeline

on: [push]

env:
  aws_access_key_id_: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_secret_access_key_: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  sam_template: template.yaml
  testing_stack_name: test-stack
  testing_deployer_role: arn:aws:iam::191762412092:role/stage-resource-stack-DeployerRole-F3UDMRJEAPVP
  testing_cfn_deployment_role: arn:aws:iam::191762412092:role/stage-resource-stack-CFNDeploymentRole-1LHD5N7FSUGB6
  testing_artifacts_bucket: stage-resource-stack-artifactsbucket-1t96af9pkc631
  testing_ecr_repo: 191762412092.dkr.ecr.us-east-2.amazonaws.com/test
  testing_region: us-east-2
  prod_stack_name: prod-stack
  prod_deployer_role: arn:aws:iam::013714286599:role/stack-resource-stack-DeployerRole-1MKUWNLR7G6I9
  prod_cfn_deployment_role: arn:aws:iam::013714286599:role/stack-resource-stack-CFNDeploymentRole-1UHQLSY8D9LY1
  prod_artifacts_bucket: stack-resource-stack-artifactsbucket-1tecc3mhymec7
  prod_ecr_repo: 013714286599.dkr.ecr.us-east-2.amazonaws.com/test
  prod_region: us-east-2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # uncomment and modify the following step for running the unit-tests
          # Assuming python runtime
          # pip install pytest
          # pip install -r /path/to/requirements.txt
          # python -m pytest /path/to/unit-tests
  
  build-and-deploy-feature:
    if: startsWith(github.ref, 'refs/heads/feature')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          . cicd/assume-role.sh ${testing_region}\
                                ${testing_deployer_role}\
                                feature-deployment
          sam build --template ${sam_template} --use-container
          sam deploy --stack-name features-${GITHUB_REF##*/}-cfn-stack \
            --capabilities CAPABILITY_IAM \
            --region ${testing_region} \
            --s3-bucket ${testing_artifacts_bucket} \
            --image-repository ${testing_ecr_repo} \
            --no-fail-on-empty-changeset \
            --role-arn ${testing_cfn_deployment_role}
  
  build:
    if: github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build resources
        run: sam build --template ${sam_template} --use-container
      - name: Upload artifacts to testing artifact buckets
        run: |
          . cicd/assume-role.sh ${testing_region} \
                                ${testing_deployer_role} \
                                prod-stage-packaging
          sam package \
            --s3-bucket ${testing_artifacts_bucket} \
            --image-repository ${testing_ecr_repo} \
            --region ${testing_region} \
            --output-template-file packaged-testing.yaml
      - name: Upload artifacts to production artifact buckets
        run: |
          . cicd/assume-role.sh ${prod_region} \
                                ${prod_deployer_role} \
                                prod-stage-packaging
          sam package \
            --s3-bucket ${prod_artifacts_bucket} \
            --region ${prod_region} \
            --image-repository ${prod_ecr_repo} \
            --output-template-file packaged-prod.yaml

      - uses: actions/upload-artifact@v2
        with:
          name: packaged-testing.yaml
          path: packaged-testing.yaml
          retention-days: 365
      - uses: actions/upload-artifact@v2
        with:
          name: packaged-prod.yaml
          path: packaged-prod.yaml
          retention-days: 365
    
  deploy-testing:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: packaged-testing.yaml
      - name: Deploy to testing account
        run: |
          . cicd/assume-role.sh ${testing_region} \
                                ${testing_deployer_role} \
                                testing-deployment
          sam deploy --stack-name ${testing_stack_name} \
            --template packaged-testing.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${testing_region} \
            --s3-bucket ${testing_artifacts_bucket} \
            --image-repository ${testing_ecr_repo} \
            --no-fail-on-empty-changeset \
            --role-arn ${testing_cfn_deployment_role}
  
  integration-test:
    if: github.ref == 'refs/heads/main'
    needs: [deploy-testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # trigger the integration tests here
  
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: [integration-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: packaged-prod.yaml
      - name: Deploy to production account
        run: |
          . cicd/assume-role.sh ${prod_region} \
                                ${prod_deployer_role} \
                                prod-deployment
          sam deploy --stack-name ${prod_stack_name} \
            --template packaged-prod.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${prod_region} \
            --s3-bucket ${prod_artifacts_bucket} \
            --image-repository ${prod_ecr_repo} \
            --no-fail-on-empty-changeset \
            --role-arn ${prod_cfn_deployment_role}
